spring:
  datasource:
    url: jdbc:mysql://localhost/maven
    username: root
    password : ps123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
server:
  port: 8889
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

